language: python
python:
  - "3.6"
cache: pip
install:
 - pip install pygame
 - pip install pylsl
 - pip install mne
 - pip install pyqt5
 - pip install scipy
 - pip install matplotlib
script:
  - pytest
